---
title: whiz.host
description: Coming Soon!
locale: en
author: 
countdown:
  theme: flat-colors-wide
  year: 2016
  month: 2
  day: 1
  hour: 0
  minute: 0
color1: '"#FFE181"'
color2: '"#EEE9E5"'
color3: '"#FAD3B2"'
color4: '"#FFBA7F"'
color5: '"#FF9C97"'
owner:
  name: siteCo.xyz
  email: xyzsiteco@gmail.com
  twitter: xyzsiteco
  facebook: xyzsiteco
  google_plus: xyzsiteco
  instagram: xyzsiteco
  url: http://siteco.xyz
  aboutlink:
    url: 
    caption: 
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
kramdown:
  toc_levels: 1..2
highlighter: rouge
exclude:
- lib
- config.rb
- ".sass-cache"
- Capfile
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- "*.sublime-project"
- "*.sublime-workspace"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- node_modules
- Gruntfile.js
- package.json
theme_num: '99'
